export const mailTypes = {
  GET_REQUEST: 'GET_DATA_REQUESTED',
  GET_SUCCESS: 'GET_DATA_SUCCESSFUL',
  GET_FAILURE: 'GET_DATA_FAILED',

  SEND_REQUEST: 'SEND_MAIL_REQUESTED',
  SEND_SUCCESS: 'SEND_MAIL_SUCCESSFULL',
  SEND_FAILURE: 'SEND_MAIL_FAILURE'
};
